image:
#- Visual Studio 2017
- Visual Studio 2015
#- Ubuntu1804
#- macos


configuration: Release

platform:
- x64
- x86

cache:
- externals/OpenSceneGraph
- resources/models
    
before_build:
  - cmd: gitversion /l console /output buildserver
  
  - ps: |
        echo "const char* ESMINI_BUILD_VERSION=`"$env:APPVEYOR_BUILD_VERSION`";"  | Out-File -Encoding "UTF8" EnvironmentSimulator/CommonMini/buildnr.cpp
        echo "buildnr created:"
        type EnvironmentSimulator/CommonMini/buildnr.cpp

# publish package on tag build
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: esmini $(GitVersion_MajorMinorPatch) (build $(APPVEYOR_BUILD_NUMBER))
    description: 'Demo and binaries'
    auth_token:
      secure: 'Zsjm85fzs4eTdDJg1VB+Y8Lk+5bEJRBkeaEtYtnbtv2IUg1sanoQTub/55QYNBsY'
    on:
       APPVEYOR_REPO_TAG: true       # deploy on tag push only
    
for:
  -
    matrix:
      only:
        - image: Ubuntu1804
    init:
      - echo Ubuntu build script
      - sh: >-
          sudo apt-get install -y libgl1-mesa-dev libxrandr-dev libxinerama-dev
          
    build_script:
      - sh: >-
          ./create_ubuntu_gcc_project.sh
          
          cd build
          
          make -j4 install
          
    after_build:
      - sh: >-
          cd ..
          
          zip -r esmini-bin_ubuntu.zip bin EnvironmentSimulator/RoadManagerDLL/roadmanagerdll.hpp EnvironmentSimulator/ScenarioEngineDLL/scenarioenginedll.hpp version.txt
          
          chmod -R +x ./run/*

          ./generate_binary_dist.sh

          mv esmini-demo.zip esmini-demo_ubuntu.zip 
              
    artifacts:
      - path: esmini-*_ubuntu.zip
        name: ubuntu_artifacts

  -
    matrix:
      only:
        - image: macos

    build_script:
      - echo MacOS Catalina build script
      - sh: >-
          chmod +x create_xcode_project.sh
          
          ./create_xcode_project.sh
          
          cd build
          
          xcodebuild -scheme install -configuration Release build
          
      - ps: |
          echo Content of version.cpp:
          type ../EnvironmentSimulator/CommonMini/version.cpp
          echo Content of buildnr.cpp:
          type ../EnvironmentSimulator/CommonMini/buildnr.cpp

    after_build:
      - sh: >-
          lipo -create EnvironmentSimulator/RoadManagerDLL/Release/libRoadManagerDLL.dylib -output ../bin/RoadManagerDLL.bundle
          
          lipo -create EnvironmentSimulator/ScenarioEngineDLL/Release/libScenarioEngineDLL.dylib -output ../bin/ScenarioEngineDLL.bundle

          cd ..
          
          zip -r esmini-bin_mac_catalina.zip bin EnvironmentSimulator/RoadManagerDLL/roadmanagerdll.hpp EnvironmentSimulator/ScenarioEngineDLL/scenarioenginedll.hpp version.txt 
          
          chmod -R +x ./run/*

          ./generate_binary_dist.sh

          mv esmini-demo.zip esmini-demo_mac_catalina.zip 

    artifacts:
      - path: esmini-*_mac_catalina.zip
        name: mac_catalina_artifacts

  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x64
    build_script:
      - echo Visual Studio 2017 x64 build script
      - cmd:
          mkdir buildVS15_64
          
          cd buildVS15_64
          
          cmake.exe -G "Visual Studio 15 Win64" -D USE_OSG=True ..
          
      - ps: |
          echo Content of version.cpp:
          type ../EnvironmentSimulator/CommonMini/version.cpp
          echo Content of buildnr.cpp:
          type ../EnvironmentSimulator/CommonMini/buildnr.cpp
          
      - cmd: 

          msbuild /m /property:Configuration=Release EnvironmentSimulator.sln

          cd..

          generate_binary_dist.bat

    after_build:
      - cmd:
            7z a esmini-demo_win.zip esmini-demo/*
 
            7z a esmini-bin_win_x64.zip bin/* EnvironmentSimulator/RoadManagerDLL/roadmanagerdll.hpp EnvironmentSimulator/ScenarioEngineDLL/scenarioenginedll.hpp version.txt 


    artifacts:
      - path: esmini-*_win*.zip
        name: windows_artifacts

  -
    matrix:
      only:
        - image: Visual Studio 2017
          platform: x86
    build_script:
      - echo Visual Studio 2017 x86 build script
      - cmd:
          mkdir buildVS15_32

          cd buildVS15_32

          cmake -G "Visual Studio 15" -D USE_OSG=True ..

      - ps: |
          echo Content of version.cpp:
          type ../EnvironmentSimulator/CommonMini/version.cpp
          echo Content of buildnr.cpp:
          type ../EnvironmentSimulator/CommonMini/buildnr.cpp

      - cmd:
          msbuild /m /property:Configuration=Release /p:Platform=win32 EnvironmentSimulator.sln

          cd..
          
    after_build:
      - cmd:
            7z a esmini-bin_win_x86.zip bin/* EnvironmentSimulator/RoadManagerDLL/roadmanagerdll.hpp EnvironmentSimulator/ScenarioEngineDLL/scenarioenginedll.hpp version.txt 

    artifacts:
      - path: esmini-*_win*.zip
        name: windows_artifacts
          
  -
    matrix:
      only:
        - image: Visual Studio 2015
          platform: x64
    build_script:
      - echo Visual Studio 2015 x64 build script
      - cmd:
          mkdir buildVS14_winsdk71_64

          cd buildVS14_winsdk71_64

          cmake -G "Visual Studio 14 2015 Win64" -T "Windows7.1SDK" -D WINSDK7_1=True -D USE_OSG=True ..

      - ps: |
          echo Content of version.cpp:
          type ../EnvironmentSimulator/CommonMini/version.cpp
          echo Content of buildnr.cpp:
          type ../EnvironmentSimulator/CommonMini/buildnr.cpp

      - cmd:
          msbuild /m /property:Configuration=Release EnvironmentSimulator.sln

          cd..
          
    after_build:
      - cmd:
            7z a esmini-bin_win_sdk7-1_x64.zip bin/* EnvironmentSimulator/RoadManagerDLL/roadmanagerdll.hpp EnvironmentSimulator/ScenarioEngineDLL/scenarioenginedll.hpp version.txt 

    artifacts:
      - path: esmini-*_win*.zip
        name: windows_artifacts
          
  -
    matrix:
      exclude:
        - image: Ubuntu1804
          platform: x86
        - image: macos-mojave
          platform: x86
        - image: macos
          platform: x86
        - image: Visual Studio 2015
          platform: x86
